# Generated by Django 3.0.10 on 2020-10-22 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SbAsfFootprint',
            fields=[
                ('county_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('county_name', models.CharField(blank=True, max_length=45, null=True)),
                ('county_state', models.CharField(blank=True, max_length=45, null=True)),
                ('frequency', models.DecimalField(blank=True, decimal_places=15, max_digits=15, null=True)),
            ],
            options={
                'db_table': 'SB_ASF_footprint',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SbQuote',
            fields=[
                ('quote_id', models.AutoField(primary_key=True, serialize=False)),
                ('quote_name', models.CharField(max_length=100)),
                ('quote_datetime', models.DateTimeField(blank=True)),
                ('quote_optype', models.CharField(db_column='quote_OpType', max_length=100)),
                ('quote_flowtype', models.CharField(db_column='quote_FlowType', max_length=100)),
                ('quote_totsowhead', models.IntegerField(db_column='quote_TotSowHead')),
                ('quote_totmarkethead', models.IntegerField(db_column='quote_TotMarketHead')),
                ('quote_totpprm', models.DecimalField(blank=True, db_column='quote_TotPPrm', decimal_places=2, max_digits=27, null=True)),
                ('quote_qprm', models.DecimalField(blank=True, db_column='quote_QPrm', decimal_places=2, max_digits=27, null=True)),
                ('quote_sgcomm', models.DecimalField(blank=True, db_column='quote_SGComm', decimal_places=2, max_digits=3, null=True)),
                ('quote_lydcomm', models.DecimalField(blank=True, db_column='quote_LydComm', decimal_places=2, max_digits=3, null=True)),
                ('quote_netprm', models.DecimalField(blank=True, db_column='quote_NetPrm', decimal_places=2, max_digits=27, null=True)),
                ('quote_accepted', models.IntegerField(blank=True, null=True)),
                ('quote_accepted_datetime', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'SB_quote',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SbQuoteLoccvg',
            fields=[
                ('quote_loc_id', models.AutoField(primary_key=True, serialize=False)),
                ('quote_loc_type', models.CharField(blank=True, max_length=45, null=True)),
                ('quote_head', models.PositiveIntegerField(db_column='quote_Head')),
                ('quote_headtype', models.CharField(db_column='quote_HeadType', max_length=45)),
                ('quote_loc_adr_string', models.TextField(blank=True, null=True)),
                ('quote_loc_street', models.CharField(blank=True, max_length=45, null=True)),
                ('quote_loc_city', models.CharField(blank=True, max_length=45, null=True)),
                ('quote_loc_county', models.CharField(blank=True, max_length=45, null=True)),
                ('quote_loc_state', models.CharField(blank=True, max_length=45, null=True)),
                ('quote_loc_postcode', models.CharField(blank=True, max_length=45, null=True)),
                ('quote_loc_country', models.CharField(blank=True, max_length=45, null=True)),
                ('quote_loc_lat', models.DecimalField(decimal_places=8, max_digits=10)),
                ('quote_loc_long', models.DecimalField(decimal_places=8, max_digits=11)),
                ('quote_cov1_bin', models.BooleanField(db_column='quote_Cov1_Bin')),
                ('quote_cov1_val', models.DecimalField(blank=True, db_column='quote_Cov1_Val', decimal_places=2, max_digits=27, null=True)),
                ('quote_cov1_dur', models.DecimalField(blank=True, db_column='quote_Cov1_Dur', decimal_places=2, max_digits=27, null=True)),
                ('quote_cov1_pprm', models.DecimalField(blank=True, db_column='quote_Cov1_PPrm', decimal_places=2, max_digits=27, null=True)),
                ('quote_cov2_bin', models.BooleanField(db_column='quote_Cov2_Bin')),
                ('quote_cov2_val', models.DecimalField(blank=True, db_column='quote_Cov2_Val', decimal_places=2, max_digits=27, null=True)),
                ('quote_cov2_dur', models.DecimalField(blank=True, db_column='quote_Cov2_Dur', decimal_places=2, max_digits=27, null=True)),
                ('quote_cov2_pprm', models.DecimalField(blank=True, db_column='quote_Cov2_PPrm', decimal_places=2, max_digits=27, null=True)),
                ('quote_cov3_bin', models.BooleanField(db_column='quote_Cov3_Bin')),
                ('quote_cov3_val', models.DecimalField(blank=True, db_column='quote_Cov3_Val', decimal_places=2, max_digits=27, null=True)),
                ('quote_cov3_dur', models.DecimalField(blank=True, db_column='quote_Cov3_Dur', decimal_places=2, max_digits=27, null=True)),
                ('quote_cov3_pprm', models.DecimalField(blank=True, db_column='quote_Cov3_PPrm', decimal_places=2, max_digits=27, null=True)),
                ('quote_cov4_bin', models.BooleanField(db_column='quote_Cov4_Bin')),
                ('quote_cov4_val', models.DecimalField(blank=True, db_column='quote_Cov4_Val', decimal_places=2, max_digits=27, null=True)),
                ('quote_cov4_dur', models.DecimalField(blank=True, db_column='quote_Cov4_Dur', decimal_places=2, max_digits=27, null=True)),
                ('quote_cov4_pprm', models.DecimalField(blank=True, db_column='quote_Cov4_PPrm', decimal_places=2, max_digits=27, null=True)),
                ('quote_cov5_bin', models.BooleanField(db_column='quote_Cov5_Bin')),
                ('quote_cov5_val', models.DecimalField(blank=True, db_column='quote_Cov5_Val', decimal_places=2, max_digits=27, null=True)),
                ('quote_cov5_dur', models.DecimalField(blank=True, db_column='quote_Cov5_Dur', decimal_places=2, max_digits=27, null=True)),
                ('quote_cov5_pprm', models.DecimalField(blank=True, db_column='quote_Cov5_PPrm', decimal_places=2, max_digits=27, null=True)),
                ('quote_cov6_bin', models.BooleanField(db_column='quote_Cov6_Bin')),
                ('quote_cov6_val', models.DecimalField(blank=True, db_column='quote_Cov6_Val', decimal_places=2, max_digits=27, null=True)),
                ('quote_cov6_dur', models.DecimalField(blank=True, db_column='quote_Cov6_Dur', decimal_places=2, max_digits=27, null=True)),
                ('quote_cov6_pprm', models.DecimalField(blank=True, db_column='quote_Cov6_PPrm', decimal_places=2, max_digits=27, null=True)),
                ('quote_county_id', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'SB_quote_loccvg',
                'managed': False,
            },
        ),
    ]
